repository: PASSK3YS/PASSK3YS.github.io

title: kieran.colfer.net
url: "https://kieran.colfer.net"
markdown: kramdown
permalink: /blog/:title/

collections:
  docs:
    output: true
    permalink: /docs/:title/

plugins:
  - jekyll-feedgit add _config.yml